### PR TITLE
Fix create dataset API path

### PR DESCRIPTION
**Pull request by thomasyu888**

### CODE REVIEW

**Comment by tschaffter** [comment]
## Notes

- [ ] Rename `DataNodeApiClient` to `DataNodeClient`

**Comment by tschaffter** [comment]
- [ ] Show more information when error occurs because a dataset with the same ID already exists in the data node

```
from nlpsandboxclient.api_client import DataNodeApiClient

nlp = DataNodeApiClient(host="http://192.168.48.3:8080/api/v1")

# for dataset in nlp.list_datasets():
#   print(dataset.)

new_dataset = nlp.create_dataset(dataset_id="my-dataset")
```

Current output:

```
HTTPError: [Errno Conflict] <Response [409]>

Detailed traceback: 
  File "<string>", line 1, in <module>
  File "/opt/miniconda/envs/sage/lib/python3.8/site-packages/nlpsandbox_client-0.2.1-py3.8.egg/nlpsandboxclient/api_client.py", line 116, in create_dataset
    dataset = self.rest_post(f"/datasets?datasetId={dataset_id}",
  File "/opt/miniconda/envs/sage/lib/python3.8/site-packages/nlpsandbox_client-0.2.1-py3.8.egg/nlpsandboxclient/api_client.py", line 57, in rest_post
    response = self._rest_call(
  File "/opt/miniconda/envs/sage/lib/python3.8/site-packages/nlpsandbox_client-0.2.1-py3.8.egg/nlpsandboxclient/api_client.py", line 83, in _rest_call
    utils._raise_for_status(response)
  File "/opt/miniconda/envs/sage/lib/python3.8/site-packages/nlpsandbox_client-0.2.1-py3.8.egg/nlpsandboxclient/utils.py", line 13, in _raise_for_status
    raise HTTPError(response.json()['title'], response)
```

**Comment by thomasyu888** [comment]
Can we file a issue instead? This way we can keep this PR small

**Comment by tschaffter** [comment]
Let put this ticket on hold as we investigate reusing code generated by the openapi generator.

**Pull request merged**
